import * as ImagePicker from "expo-image-picker";
import { useCallback, useState } from "react";
import { Platform, StyleSheet, Switch, Text, View } from "react-native";
import { Image } from "expo-image";
import { Redirect, useFocusEffect } from "expo-router";
import { Button, Card, Input, Screen, Title, ui } from "../../src/components/UI";
import { F4WEAlert as Alert } from "../../src/components/F4WEAlert";
import { useAuth } from "../../src/context/AuthContext";
import { api, uploadFile, type NativeUploadFile } from "../../src/lib/api";
import { profilePictureUrl } from "../../src/lib/media";
import { colors } from "../../src/lib/theme";

type Product = { key: string; name: string; description: string; price: number; active: boolean };
type Design = { id: string; name: string; assetUrl: string; price: number; isLimited: boolean; active: boolean };
type OwnerState = { products: Product[]; designs: Design[]; rewardSettings: { intervalSeconds: number; coinAmount: number } };

export default function OwnerPortal() {
  const { user } = useAuth();
  const [state, setState] = useState<OwnerState | null>(null), [busy, setBusy] = useState(false);
  const [coinUserId, setCoinUserId] = useState(""), [coinAmount, setCoinAmount] = useState("");
  const [minutes, setMinutes] = useState("3"), [rewardCoins, setRewardCoins] = useState("1");
  const [designName, setDesignName] = useState(""), [designPrice, setDesignPrice] = useState(""), [limited, setLimited] = useState(false), [designFile, setDesignFile] = useState<NativeUploadFile | null>(null);
  const [prices, setPrices] = useState<Record<string, string>>({}), [designNames, setDesignNames] = useState<Record<string, string>>({});
  const load = useCallback(async () => { try { const value = await api<OwnerState>("/api/shop?manage=true"); setState(value); setMinutes(String(Math.round(value.rewardSettings.intervalSeconds / 60))); setRewardCoins(String(value.rewardSettings.coinAmount)); setPrices(Object.fromEntries([...value.products.map(item => [item.key, String(item.price)]), ...value.designs.map(item => [item.id, String(item.price)])])); setDesignNames(Object.fromEntries(value.designs.map(item => [item.id, item.name]))); } catch (e) { Alert.alert("Could not load Owner Portal", e instanceof Error ? e.message : "Try again"); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (!user?.isOwner) return <Redirect href="/(tabs)/profile" />;
  const adjustCoins = async (sign: 1 | -1) => { const value = Number(coinAmount); if (!/^\d{16}$/.test(coinUserId) || !Number.isInteger(value) || value <= 0) return Alert.alert("Invalid values", "Enter a 16-digit app ID and a positive whole coin amount."); setBusy(true); try { const updated = await api<{ username: string; coins: number }>("/api/shop/owner/coins", { method: "POST", body: JSON.stringify({ userId: coinUserId, amount: sign * value }) }); Alert.alert("Balance updated", `${updated.username}: ${updated.coins} coins`); setCoinAmount(""); } catch (e) { Alert.alert("Could not change coins", e instanceof Error ? e.message : "Try again"); } finally { setBusy(false); } };
  const saveRewards = async () => { const intervalMinutes = Number(minutes), coinAmountValue = Number(rewardCoins); if (!Number.isInteger(intervalMinutes) || intervalMinutes < 1 || !Number.isInteger(coinAmountValue) || coinAmountValue < 1) return Alert.alert("Invalid reward settings"); setBusy(true); try { await api("/api/shop/owner/reward-settings", { method: "PATCH", body: JSON.stringify({ intervalMinutes, coinAmount: coinAmountValue }) }); await load(); } catch (e) { Alert.alert("Could not save rewards", e instanceof Error ? e.message : "Try again"); } finally { setBusy(false); } };
  const chooseDesign = async () => { if (Platform.OS === "ios") { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: false, quality: 1 }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; if (asset.fileSize && asset.fileSize > 5 * 1024 * 1024) return Alert.alert("File too large", "Maximum size is 5 MB."); setDesignFile({ uri: asset.uri, name: asset.fileName || "profile-design.png", type: asset.mimeType || "image/png", size: asset.fileSize }); };
  const addDesign = async () => { const price = Number(designPrice); if (!designFile || !designName.trim() || !Number.isInteger(price) || price < 0) return Alert.alert("Missing design data", "Choose an image/GIF and enter a name plus a whole price."); setBusy(true); try { await uploadFile("/api/shop/owner/designs", designFile, { name: designName.trim(), price, isLimited: limited }); setDesignFile(null); setDesignName(""); setDesignPrice(""); setLimited(false); await load(); } catch (e) { Alert.alert("Could not add design", e instanceof Error ? e.message : "Try again"); } finally { setBusy(false); } };
  const updateProduct = async (product: Product, active = product.active) => { const price = Number(prices[product.key]); if (!Number.isInteger(price) || price < 0) return Alert.alert("Invalid price"); setBusy(true); try { await api(`/api/shop/owner/products/${product.key}`, { method: "PATCH", body: JSON.stringify({ price, active }) }); await load(); } catch (e) { Alert.alert("Could not update product", e instanceof Error ? e.message : "Try again"); } finally { setBusy(false); } };
  const updateDesign = async (design: Design, changes: Partial<Design> = {}) => { const price = Number(prices[design.id]), name = designNames[design.id]?.trim(); if (!name || !Number.isInteger(price) || price < 0) return Alert.alert("Invalid design name or price"); setBusy(true); try { await api(`/api/shop/owner/designs/${design.id}`, { method: "PATCH", body: JSON.stringify({ name, price, ...changes }) }); await load(); } catch (e) { Alert.alert("Could not update design", e instanceof Error ? e.message : "Try again"); } finally { setBusy(false); } };
  const removeDesign = (design: Design) => Alert.alert("Delete design?", "Existing owners will also lose this frame.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => { setBusy(true); void api(`/api/shop/owner/designs/${design.id}`, { method: "DELETE" }).then(load).catch(e => Alert.alert("Could not delete design", e.message)).finally(() => setBusy(false)); } }]);
  return <Screen><Title subtitle="Owner-only controls for rewards, products, and profile designs.">Owner Portal</Title>
    <Text style={ui.section}>F4WE Coin Add / Remove</Text><Input placeholder="16-digit app user ID" keyboardType="number-pad" value={coinUserId} onChangeText={setCoinUserId} maxLength={16} /><Input placeholder="Coin amount" keyboardType="number-pad" value={coinAmount} onChangeText={setCoinAmount} /><View style={[ui.row, { gap: 8 }]}><View style={{ flex: 1 }}><Button title="Add coins" loading={busy} onPress={() => void adjustCoins(1)} /></View><View style={{ flex: 1 }}><Button title="Remove coins" tone="dark" loading={busy} onPress={() => void adjustCoins(-1)} /></View></View>
    <Text style={ui.section}>Reward Settings</Text><Card><Text style={ui.label}>Minutes per reward</Text><Input keyboardType="number-pad" value={minutes} onChangeText={setMinutes} /><Text style={ui.label}>Coins per reward</Text><Input keyboardType="number-pad" value={rewardCoins} onChangeText={setRewardCoins} /><Button title="Save reward settings" loading={busy} onPress={() => void saveRewards()} /></Card>
    <Text style={ui.section}>Base Shop Products</Text>{state?.products.map(product => <Card key={product.key}><Text style={[ui.body, { fontWeight: "900" }]}>{product.name}</Text><Text style={ui.label}>Price</Text><Input keyboardType="number-pad" value={prices[product.key] || ""} onChangeText={value => setPrices(current => ({ ...current, [product.key]: value }))} /><View style={[ui.row, { justifyContent: "space-between", marginBottom: 10 }]}><Text style={ui.body}>{product.active ? "Active" : "Inactive"}</Text><Switch value={product.active} onValueChange={active => void updateProduct(product, active)} trackColor={{ true: colors.softRed }} /></View><Button title="Save price" tone="dark" loading={busy} onPress={() => void updateProduct(product)} /></Card>)}
    <Text style={ui.section}>Design Add</Text><Card>{designFile ? <Image source={{ uri: designFile.uri }} style={styles.preview} contentFit="contain" /> : null}<Button title={designFile ? "Change image / GIF" : "Choose image / GIF"} tone="dark" onPress={() => void chooseDesign()} /><Text style={ui.label}>Design name</Text><Input value={designName} onChangeText={setDesignName} maxLength={80} /><Text style={ui.label}>Price</Text><Input keyboardType="number-pad" value={designPrice} onChangeText={setDesignPrice} /><View style={[ui.row, { justifyContent: "space-between", marginBottom: 12 }]}><Text style={ui.body}>Limited Edition</Text><Switch value={limited} onValueChange={setLimited} trackColor={{ true: colors.gold }} /></View><Button title="Publish design" loading={busy} onPress={() => void addDesign()} /></Card>
    <Text style={ui.section}>Design Manager</Text>{state?.designs.map(design => <Card key={design.id}><View style={[ui.row, { gap: 12 }]}><Image source={{ uri: profilePictureUrl(design.assetUrl) }} style={styles.design} contentFit="contain" /><View style={{ flex: 1 }}><Text style={[ui.body, { fontWeight: "900" }]}>{design.name}</Text><Text style={ui.muted}>{design.isLimited ? "Limited Edition" : "Standard"}</Text></View></View><Text style={ui.label}>Name</Text><Input value={designNames[design.id] || ""} onChangeText={value => setDesignNames(current => ({ ...current, [design.id]: value }))} maxLength={80} /><Text style={ui.label}>Price</Text><Input keyboardType="number-pad" value={prices[design.id] || ""} onChangeText={value => setPrices(current => ({ ...current, [design.id]: value }))} /><View style={[ui.row, { justifyContent: "space-between" }]}><Text style={ui.body}>Available</Text><Switch value={design.active} onValueChange={active => void updateDesign(design, { active })} trackColor={{ true: colors.softRed }} /></View><View style={[ui.row, { justifyContent: "space-between", marginBottom: 10 }]}><Text style={ui.body}>Limited Edition</Text><Switch value={design.isLimited} onValueChange={isLimited => void updateDesign(design, { isLimited })} trackColor={{ true: colors.gold }} /></View><Button title="Save name and price" tone="dark" loading={busy} onPress={() => void updateDesign(design)} /><View style={{ height: 8 }} /><Button title="Delete design" tone="red" loading={busy} onPress={() => removeDesign(design)} /></Card>)}
  </Screen>;
}
const styles = StyleSheet.create({ preview: { width: 130, height: 130, alignSelf: "center", marginBottom: 12 }, design: { width: 76, height: 76, backgroundColor: colors.raised, borderRadius: 38 } });
