import * as Clipboard from "expo-clipboard";
import { useCallback, useState } from "react";
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { Redirect, useFocusEffect } from "expo-router";
import { Button, Card, Input, Screen, Title, ui } from "../../src/components/UI";
import { F4WEAlert as Alert } from "../../src/components/F4WEAlert";
import { useAuth } from "../../src/context/AuthContext";
import { api } from "../../src/lib/api";
import { profilePictureUrl } from "../../src/lib/media";
import { colors } from "../../src/lib/theme";

type Product = { key: "invite_code" | "animated_profile" | "animated_banner"; name: string; description: string; price: number; active: boolean };
type Design = { id: string; name: string; assetUrl: string; price: number; isLimited: boolean; active: boolean; owned: boolean; using: boolean };
type ShopState = { user: { coins: number; animatedProfileUnlocked: boolean; animatedBannerUnlocked: boolean; activeProfileDesignId: string | null }; products: Product[]; designs: Design[]; invites: { accessKey: string; createdAt: string; access: { used: boolean; usedCount: number } }[]; rewardSettings: { intervalSeconds: number; coinAmount: number } };

export default function Shop() {
  const { user, refresh } = useAuth(); const [state, setState] = useState<ShopState | null>(null), [busy, setBusy] = useState<string | null>(null); const [calculatorOpen, setCalculatorOpen] = useState(false), [targetCoins, setTargetCoins] = useState("");
  const load = useCallback(async (quiet = false) => { try { setState(await api<ShopState>("/api/shop")); } catch (e) { if (!quiet) Alert.alert("Could not load shop", e instanceof Error ? e.message : "Try again"); } }, []);
  useFocusEffect(useCallback(() => { void load(); const timer = setInterval(() => void load(true), 10_000); return () => clearInterval(timer); }, [load]));
  if (!user) return <Redirect href="/login" />;
  const buyProduct = (product: Product) => Alert.alert(`Buy ${product.name}?`, `${product.price} F4WE COIN will be deducted.`, [{ text: "Cancel" }, { text: "Buy", onPress: () => { setBusy(product.key); void api<{ inviteCode?: string }>(`/api/shop/purchase/${product.key}`, { method: "POST" }).then(async result => { await Promise.all([load(), refresh()]); Alert.alert("Purchase complete", result.inviteCode ? `Your one-use invite code is ${result.inviteCode}` : "Your lifetime feature is now unlocked."); }).catch(e => Alert.alert("Purchase failed", e.message)).finally(() => setBusy(null)); } }]);
  const updateDesign = (design: Design) => { const path = design.using ? "/api/shop/designs/active" : `/api/shop/designs/${design.id}/${design.owned ? "use" : "purchase"}`; setBusy(design.id); void api(path, { method: design.using ? "DELETE" : "POST" }).then(async () => { await Promise.all([load(), refresh()]); }).catch(e => Alert.alert("Could not update design", e.message)).finally(() => setBusy(null)); };
  const wanted = Math.max(0, Number(targetCoins) || 0), settings = state?.rewardSettings, secondsNeeded = settings ? Math.ceil(wanted / settings.coinAmount) * settings.intervalSeconds : 0;
  const durationText = secondsNeeded ? `${Math.floor(secondsNeeded / 86400)}d ${Math.floor(secondsNeeded % 86400 / 3600)}h ${Math.floor(secondsNeeded % 3600 / 60)}m` : "Enter a coin amount";
  return <Screen><View style={[ui.row, { alignItems: "flex-start" }]}><View style={{ flex: 1 }}><Title subtitle="Earn coins while listening and unlock lifetime profile features.">F4WE Shop</Title></View><Pressable accessibilityLabel="Open listening time calculator" onPress={() => setCalculatorOpen(true)} style={styles.calculator}><Ionicons name="time-outline" size={24} color={colors.text} /></Pressable></View>
    <Card><Text style={ui.muted}>YOUR BALANCE</Text><Text style={styles.balance}>{state?.user.coins ?? user.coins ?? 0} F4WE COIN</Text></Card>
    <Text style={ui.section}>Features</Text>{!state ? <ActivityIndicator color={colors.accent} /> : state.products.map(product => { const owned = product.key === "animated_profile" ? state.user.animatedProfileUnlocked : product.key === "animated_banner" ? state.user.animatedBannerUnlocked : false; return <Card key={product.key}><View style={[ui.row, { justifyContent: "space-between", gap: 12 }]}><View style={{ flex: 1 }}><Text style={[ui.body, { fontWeight: "900" }]}>{product.name}</Text><Text style={[ui.muted, { marginTop: 4 }]}>{product.description}</Text><Text style={styles.price}>{product.price} F4WE COIN</Text></View><View style={{ width: 112 }}><Button title={owned ? "Owned" : product.active ? "Buy" : "Inactive"} tone={owned || !product.active ? "dark" : "red"} loading={busy === product.key} onPress={() => !owned && product.active && buyProduct(product)} /></View></View></Card>; })}
    {state?.invites.length ? <><Text style={ui.section}>Your invite codes</Text>{state.invites.map(invite => <Pressable key={invite.accessKey} onPress={() => void Clipboard.setStringAsync(invite.accessKey).then(() => Alert.alert("Copied", "Invite code copied."))}><Card><Text style={styles.code}>{invite.accessKey}</Text><Text style={ui.muted}>{invite.access.used ? "Used" : "Available • tap to copy"}</Text></Card></Pressable>)}</> : null}
    <Text style={ui.section}>Profile Designs</Text>{state?.designs.map(design => <Card key={design.id}><View style={[ui.row, { gap: 16 }]}><View style={styles.preview}><Image source={{ uri: profilePictureUrl(design.assetUrl) }} style={styles.design} contentFit="contain" /></View><View style={{ flex: 1 }}><View style={[ui.row, { gap: 7, flexWrap: "wrap" }]}><Text style={[ui.body, { fontWeight: "900" }]}>{design.name}</Text>{design.isLimited ? <Text style={styles.limited}>LIMITED EDITION</Text> : null}{!design.active && design.owned ? <Text style={styles.retired}>OWNED • RETIRED</Text> : null}</View><Text style={styles.price}>{design.owned ? "Purchased" : `${design.price} F4WE COIN`}</Text><Button title={design.using ? "Remove" : design.owned ? "Use" : "Buy"} tone={design.using ? "dark" : "red"} loading={busy === design.id} onPress={() => updateDesign(design)} /></View></View></Card>)}{state && !state.designs.length ? <Text style={ui.muted}>No profile designs are available yet.</Text> : null}
    <Modal visible={calculatorOpen} transparent animationType="fade" onRequestClose={() => setCalculatorOpen(false)}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={[ui.section, { marginTop: 0 }]}>F4WE COIN calculator</Text><Text style={ui.muted}>How much F4WE COIN would you like to earn?</Text><Input value={targetCoins} onChangeText={setTargetCoins} keyboardType="number-pad" placeholder="500" /><Text style={styles.duration}>{durationText}</Text>{settings ? <Text style={ui.muted}>Current rate: {settings.coinAmount} F4WE COIN every {Math.round(settings.intervalSeconds / 60)} minute(s).</Text> : null}<View style={{ height: 16 }} /><Button title="Close" tone="dark" onPress={() => setCalculatorOpen(false)} /></View></View></Modal>
  </Screen>;
}
const styles = StyleSheet.create({ balance: { color: colors.softRed, fontWeight: "900", fontSize: 28, marginTop: 4 }, price: { color: colors.softRed, fontWeight: "900", marginVertical: 8 }, code: { color: colors.text, fontFamily: "monospace", fontSize: 18, fontWeight: "900", marginBottom: 5 }, preview: { width: 90, height: 90, borderRadius: 45, backgroundColor: colors.raised, alignItems: "center", justifyContent: "center" }, design: { width: 88, height: 88 }, limited: { color: colors.gold, fontSize: 10, fontWeight: "900", borderWidth: 1, borderColor: colors.gold, borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3 }, retired: { color: colors.muted, fontSize: 10, fontWeight: "900", borderWidth: 1, borderColor: colors.border, borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3 }, calculator: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.raised, alignItems: "center", justifyContent: "center", marginTop: 4 }, modalBackdrop: { flex: 1, backgroundColor: "#000B", alignItems: "center", justifyContent: "center", padding: 22 }, modalCard: { width: "100%", maxWidth: 420, backgroundColor: colors.surface, borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 20 }, duration: { color: colors.softRed, fontSize: 27, fontWeight: "900", marginVertical: 12 } });
